---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

###########################################################
# dotfile ansible role parameters
###########################################################
dotfiles_repo: https://gitlab.com/WhiteDeerStalker/dotfiles
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/repos/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc

###########################################################
# hombrew ansible role parameters
###########################################################
homebrew_installed_packages:
  # VCS
  - git
  - git-flow
  # Development
 ####- r
 ####- python@3.9
  # Editor
  - vim
  - powerline-go
  # Database
 ####- sqlite
 ####- postgresql@14
  # Other
 ####- doxygen
  - ansible
  - ssh-copy-id
 ####- pv
 ####- zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # Web browser
 ####- brave-browser
  - google-chrome
  # Development
 ####- fork
 ####- intellij-idea
 ####- rstudio
 ####- julia
 ####- atom
 ####- visual-studio-code
  # Container
 ####- docker
  # Editor
 ####- mactex
 ####- sublime-text
  # Productivity
  - zoom
 ####- slack
  - skype
 ####- discord
 ####- skype-for-business
  - teamviewer
 ####- webex-meetings
  # Trading
  - trader-workstation (beta version is installed to work best with ARM)
  # Other
 ####- raspberry-pi-imager
  - dropbox
 ####- kdrive
  - transmission
  - vlc
  - adobe-acrobat-reader
  - 1password
  - telegram-desktop
  - whatsapp
  - signal

###########################################################
# mas ansible role parameters
###########################################################
# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: "fominykhanna@gmail.com"
mas_password: vars_prompt

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []


###########################################################
# Additional note of things that couldn't be automated
###########################################################
# Install Citrix workspace: https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-latest.html
# install Garmin Express: https://www.garmin.com/en-US/software/express/mac/
# Download powerline-fonts: https://github.com/powerline/fonts
# Install of trader workstation (beta for ARM): https://www.interactivebrokers.com/en/index.php?f=5068
